spring:
  datasource:
    password: aquaM236441
    url: jdbc:postgresql://localhost:5432/homes_test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
